export default {
	login: 'john-smilga',
	id: 42133389,
	node_id: 'MDQ6VXNlcjQyMTMzMzg5',
	avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/john-smilga',
	html_url: 'https://github.com/john-smilga',
	followers_url: 'https://api.github.com/users/john-smilga/followers',
	following_url:
		'https://api.github.com/users/john-smilga/following{/other_user}',
	gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
	starred_url:
		'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
	organizations_url: 'https://api.github.com/users/john-smilga/orgs',
	repos_url: 'https://api.github.com/users/john-smilga/repos',
	events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
	received_events_url:
		'https://api.github.com/users/john-smilga/received_events',
	type: 'User',
	site_admin: false,
	name: 'John Smilga',
	company: 'Coding Addict',
	blog: 'www.johnsmilga.com',
	location: 'Los Angeles',
	email: null,
	hireable: null,
	bio: 'Creator of Coding Addict',
	twitter_username: 'john_smilga',
	public_repos: 260,
	public_gists: 52,
	followers: 20865,
	following: 31,
	created_at: '2018-08-06T06:48:23Z',
	updated_at: '2020-07-08T05:01:32Z',

	// login: 'Pamma1129',
	// id: 46252071,
	// node_id: 'MDQ6VXNlcjQ2MjUyMDcx',
	// avatar_url: 'https://avatars.githubusercontent.com/u/46252071?v=4',
	// gravatar_id: '',
	// url: 'https://api.github.com/users/Pamma1129',
	// html_url: 'https://github.com/Pamma1129',
	// followers_url: 'https://api.github.com/users/Pamma1129/followers',
	// following_url:
	// 	'https://api.github.com/users/Pamma1129/following{/other_user}',
	// gists_url: 'https://api.github.com/users/Pamma1129/gists{/gist_id}',
	// starred_url: 'https://api.github.com/users/Pamma1129/starred{/owner}{/repo}',
	// subscriptions_url: 'https://api.github.com/users/Pamma1129/subscriptions',
	// organizations_url: 'https://api.github.com/users/Pamma1129/orgs',
	// repos_url: 'https://api.github.com/users/Pamma1129/repos',
	// events_url: 'https://api.github.com/users/Pamma1129/events{/privacy}',
	// received_events_url: 'https://api.github.com/users/Pamma1129/received_events',
	// type: 'User',
	// site_admin: false,
	// name: null,
	// company: null,
	// blog: '',
	// location: null,
	// email: null,
	// hireable: null,
	// bio: null,
	// twitter_username: null,
	// public_repos: 3,
	// public_gists: 0,
	// followers: 0,
	// following: 0,
	// created_at: '2018-12-30T00:16:29Z',
	// updated_at: '2021-08-15T01:55:01Z',
};
